name: Railway Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
    deploy:
    name: Deploy to Railway
    needs: push_to_registry
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 9aba30db-78b8-48e9-aaae-c5123d25b077
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: railway up --service=${{ env.SVC_ID }}

